# Generated by Django 4.2.6 on 2023-10-24 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_productmaterials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmaterials',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='my_app.productmaterials'),
        ),
    ]
